[tool.poetry]
name = "jsave"
version = "1.4.0"
description = "A simple python module for saving data to JSON files"
authors = ["Ethan Illingsworth"]
readme = "README.md"
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.8"
tsafe = "1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
